site_name: BIT游泳社教练手册
site_url: https://bit-swimming.club/
site_description: BIT游泳社教案
site_author: BIT游泳社教案组

repo_name: BIT游泳社教练手册
repo_url: https://github.com/BITYYS/Instructor-Manual
edit_uri: ""

# nav:
# - 0.综述: 0.综述.md
# - 1.引言: 1.引言.md
# - 2.教学方法: 2.教学方法.md
# - 3.安全教育: 3.安全教育.md
# - 4.准备活动: 4.准备活动.md
# - 5.蛙泳四步教学: 5.蛙泳四步教学.md
# - 6.深水突击班: 6.深水突击班.md
# - 7.教练员培养体系: 7.教练员培养体系.md
# - 8.教案的修改及完善: 8.教案的修改及完善.md
# - 历史版本: 历史版本.md

nav:
- 主页: index.md
- 综述: 综述.md
- 教学理论:
  - 为什么要开设教学活动  : 教学理论/教学活动的意义.md
  - 教学活动中的角色: 教学理论/教学活动中的角色.md
  - 教学的现在和未来: 教学理论/教学的现在和未来.md
  - 一些注意事项: 教学理论/一些注意事项.md
  - 教学方法: 教学理论/教学方法.md
  - 安全教育: 教学理论/安全教育.md
  - 准备活动: 教学理论/准备活动.md
# - 练习库:
#   - 蛙泳四步教学: 5.蛙泳四步教学.md
#   - 深水突击班: 6.深水突击班.md
# - 初级班:
- 蛙泳四步教学: 
  - 四步教学综述: 蛙泳/四步教学综述.md
  - 完全不会: 蛙泳/完全不会阶段.md
  - 纯蛙泳腿: 蛙泳/纯蛙泳腿阶段.md
  - 呼吸蛙泳腿: 蛙泳/呼吸蛙泳腿阶段.md
  - 蛙泳配合: 蛙泳/蛙泳配合阶段.md
  - 常见问题: 蛙泳/常见问题.md
- 深水突击班:
  - 深水突击班: 深水突击班/深水突击班.md
- 自由泳教学:
  - 自由泳综述: 自由泳/自由泳综述.md
  - 自由泳腿: 自由泳/自由泳腿.md
  - 转身换气: 自由泳/转身换气.md
  - 自由泳手: 自由泳/自由泳手.md
  - 自由泳配合: 自由泳/自由泳配合.md
# - 更多内容:
- 教练员培养体系: 教练员培养体系.md
- 教案的修改完善: 教案的修改及完善.md
- 联系我们: contact.md
- 贡献者: contributors.md

copyright: Copyright &copy; 2021-2022 <a href="https://github.com/rm-rf-me">ljc</a>. Maintained by the <a href="/contributors/">BIT游泳社教案组</a>. <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>

theme:
  name: material
  # custom_dir: !ENV [THEME_DIR, "material"]
  # custom_dir: overrides/
  favicon: img/icon/favicon.ico
  logo: img/icon/favicon.png

  # font:
  #   text: Roboto
  #   code: Roboto Mono

  features:
  - navigation.instant
  - navigation.tabs
  - navigation.tabs.sticky
  - toc.integrate
  - search.suggest
  # - navigation.sections
  # - navigation.expand
  # - navigation.indexes
  # - header.autohide

  palette:
  #   primary: cyan
  #   accent: pink

  # Toggle light mode
    - scheme: default
      primary: cyan
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode


  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rm-rf-me
      
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/506080676
  
extra_css:
    - css/extra.css

plugins:
  - search:
      separator: '[\\s\\u200b\\-]'

# theme:
#     name: readthedocs

# theme:
#     name: mkdocs
#     analytics:
#         gtag: G-ABC123

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
    - pymdownx.details
    - pymdownx.superfences
    - md_in_html
    - tables
    - attr_list
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

    # - mdx_gh_links:
    #     user: mkdocs
    #     repo: mkdocs

# plugins:
#     - search
#     - redirects:
#         redirect_maps:
#             user-guide/plugins.md: dev-guide/plugins.md
#             user-guide/custom-themes.md: dev-guide/themes.md
#             user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md
